networks:
  dev-network:
    driver: bridge

services:

  simple-service:
    tty: true
    build:
      context: ./simple-service
      dockerfile: dev.Dockerfile
    volumes:
      - ./simple-service:/app
    ports:
      - "8021:8000"
    networks:
      - dev-network

  postgres:
    image: postgres:18.3
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - dev-network